#5 - Major rewrite

diff --git a/jobs/.image.gitlab-ci.yml b/jobs/.image.gitlab-ci.yml
--- a/jobs/.image.gitlab-ci.yml
+++ b/jobs/.image.gitlab-ci.yml
@@ -112,29 +112,50 @@ include:
   extends: .image-build
   stage: test
   variables:
-    IMAGE_UNITTEST_OUTPUT_DIR: /var/tmp
-    IMAGE_UNITTEST_OUTPUT_FILE: unit-test-results.xml
+    IMAGE_UNITTEST_CONTAINER_OUTPUT_DIR: /var/tmp
+    IMAGE_UNITTEST_CONTAINER_OUTPUT_FILE: unit-test-results.xml
+    IMAGE_UNITTEST_LOCAL_OUTPUT_DIR: .image-unit-test
+    IMAGE_UNITTEST_LOCAL_FILE: unit-test-results.${CI_JOB_ID}.xml
   script:
     - |
       # --- image-unit-test -------------------------------------------
-      IMAGE_UNITTEST_OUTPUT_DIR=${IMAGE_UNITTEST_OUTPUT_DIR:-/var/tmp}
-      IMAGE_UNITTEST_OUTPUT_FILE=${IMAGE_UNITTEST_OUTPUT_FILE:-unit-test-results.xml}
+      IMAGE_UNITTEST_CONTAINER_OUTPUT_DIR=${IMAGE_UNITTEST_CONTAINER_OUTPUT_DIR:-/var/tmp}
+      IMAGE_UNITTEST_CONTAINER_OUTPUT_FILE=${IMAGE_UNITTEST_CONTAINER_OUTPUT_FILE:-unit-test-results.xml}
+      IMAGE_UNITTEST_LOCAL_OUTPUT_DIR=${IMAGE_UNITTEST_LOCAL_OUTPUT_DIR:-.image-unit-test}
+      IMAGE_UNITTEST_LOCAL_FILE=${IMAGE_UNITTEST_LOCAL_FILE:-unit-test-results.${CI_JOB_ID}.xml}
+      IMAGE_UNITTEST_LOCAL_FILEPATH=${IMAGE_UNITTEST_LOCAL_OUTPUT_DIR}/${IMAGE_UNITTEST_LOCAL_FILE}
 
-      mkdir -p ./.image-unit-test
+      mkdir -p ${IMAGE_UNITTEST_LOCAL_OUTPUT_DIR}
       echo "Building unittest target..."
       podman image build "${IMAGE_BUILD_CLI_ARGS[@]}"
+
       echo "Running unittest..."
+      set +e
       podman run  --rm  \
                   --tty  \
-                  --volume .image-unit-test:${IMAGE_UNITTEST_OUTPUT_DIR}  \
+                  --volume ${IMAGE_UNITTEST_LOCAL_OUTPUT_DIR}:${IMAGE_UNITTEST_CONTAINER_OUTPUT_DIR}  \
                   ${IMAGE_AS_BUILT_URI}
+      exit_code=$?
+      set -e
 
-      mv .image-unit-test/${IMAGE_UNITTEST_OUTPUT_FILE} .image-unit-test/unit-test-results.${CI_JOB_ID}.xml
+      if [[ -f ${IMAGE_UNITTEST_LOCAL_OUTPUT_DIR}/${IMAGE_UNITTEST_CONTAINER_OUTPUT_FILE} ]]; then
+        mv  ${IMAGE_UNITTEST_LOCAL_OUTPUT_DIR}/${IMAGE_UNITTEST_CONTAINER_OUTPUT_FILE}  ${IMAGE_UNITTEST_LOCAL_FILEPATH}
+      fi
+
+      if [[ ${exit_code} -ne 0 ]] ; then
+        echo "❌  unit test FAILED"
+
+        if [[ -f ${IMAGE_UNITTEST_LOCAL_FILEPATH} ]]; then
+          xq --color ${IMAGE_UNITTEST_LOCAL_FILEPATH}
+        fi
+
+        exit ${exit_code}
+      fi
   artifacts:
     paths:
-      - .image-unit-test/unit-test-results.${CI_JOB_ID}.xml
+      - ${IMAGE_UNITTEST_LOCAL_OUTPUT_DIR}/${IMAGE_UNITTEST_LOCAL_FILE}
     reports:
-      junit: .image-unit-test/unit-test-results.${CI_JOB_ID}.xml
+      junit: ${IMAGE_UNITTEST_LOCAL_OUTPUT_DIR}/${IMAGE_UNITTEST_LOCAL_FILE}
     when: always
     expire_in: 1 week
 
@@ -151,12 +172,16 @@ include:
     - |
       # --- image-structure-test (before_script) -----------------------------
       echo "Running Podman service..."
-      PODMAN_CI_JOB_SOCKET_RETRIES=5
+
+      # NOTE: Since the podman service is run in the background, the socket
+      #       may not be ready immediately.  Below, we perform a few waits
+      #       to allow the service to start.
+      PODMAN_CI_JOB_SOCKET_MAX_WAIT_RETRIES=5
       PODMAN_CI_JOB_SOCKET=/var/tmp/podman-${CI_JOB_ID}.sock
       export DOCKER_HOST=unix://${PODMAN_CI_JOB_SOCKET}
       podman system service --time=30 ${DOCKER_HOST} &
 
-      for i in {1..${PODMAN_CI_JOB_SOCKET_RETRIES}}; do
+      for i in $(seq 1 ${PODMAN_CI_JOB_SOCKET_MAX_WAIT_RETRIES}); do
         if [[ -e ${PODMAN_CI_JOB_SOCKET} ]]; then
           break
         fi
@@ -165,7 +190,7 @@ include:
       done
 
       if [[ ! -e ${PODMAN_CI_JOB_SOCKET} ]]; then
-        echo "❌  Podman socket not created after ${PODMAN_CI_JOB_SOCKET_RETRIES}s"
+        echo "❌  Podman socket not created after ${PODMAN_CI_JOB_SOCKET_MAX_WAIT_RETRIES}s"
         exit 1
       fi
 
@@ -191,12 +216,16 @@ include:
 
       set +e
       container-structure-test "${CST_CLI_ARGS[@]}"
-      cst_exit_code=$?
+      exit_code=$?
       set -e
-      if [[ ${cst_exit_code} -ne 0 ]] ; then
+      if [[ ${exit_code} -ne 0 ]] ; then
         echo "❌  container-structure-test FAILED"
-        xq --color ${CST_REPORT_FILEPATH}
-        exit ${cst_exit_code}
+
+        if [[ -f ${CST_REPORT_FILEPATH} ]]; then
+          xq --color ${CST_REPORT_FILEPATH}
+        fi
+
+        exit ${exit_code}
       fi
   artifacts:
     paths:
@@ -221,41 +250,49 @@ include:
       # --- image-promote ----------------------------------------------------
 
       RELEASE_README_FILEPATH=.release/image.${CI_JOB_ID}.md
-      mkdir $(dirname ${RELEASE_README_FILEPATH})
+      mkdir -p $(dirname ${RELEASE_README_FILEPATH})
 
       echo "### Image: ${IMAGE_BUILD_NAME}" >> ${RELEASE_README_FILEPATH}
 
-      IMAGE_TAGS=()
-      IMAGE_TAGS+=(${CI_COMMIT_REF_SLUG})
+      IMAGE_TAG_VARS=()
+      IMAGE_TAG_VARS+=(CI_COMMIT_REF_SLUG)
 
-      if [[ "${IMAGE_PROMOTE_RELEASE_TRAIN}" == "true" && -n "${RELEASE_TRAIN}" ]]; then
-        IMAGE_TAGS+=(${RELEASE_TRAIN})
+      if [[ "${IMAGE_PROMOTE_RELEASE_TRAIN}" == "true" ]]; then
+        IMAGE_TAG_VARS+=(RELEASE_TRAIN)
       fi
 
       if [[ "${IMAGE_PROMOTE_SEMANTIC_VERSION}" == "true" ]]; then
-        # Image tags may not contain the '+' character (from SemVer build metadata)
-        SEMANTIC_VERSION_SLUG=${SEMANTIC_VERSION//+/.}
-        IMAGE_TAGS+=(${SEMANTIC_VERSION_SLUG})
+        IMAGE_TAG_VARS+=(SEMANTIC_VERSION_SLUG)
       fi
 
-      for tag in ${IMAGE_TAGS[@]}; do
-        IMAGE_PUSH_URI=${IMAGE_AS_BUILT_URI/%${IMAGE_AS_BUILT_VERSION}/${tag}}
+      for tag_var in ${IMAGE_TAG_VARS[@]}; do
+        image_tag=${!tag_var}
 
-        echo "Copying image to ${IMAGE_PUSH_URI}..."
-        skopeo copy --quiet docker://${IMAGE_AS_BUILT_URI}  docker://${IMAGE_PUSH_URI}
+        if [[ -z "${image_tag}" ]]; then
+          continue
+        fi
 
-        image_tag_human_readable_label=${tag#CI_}
-        image_tag_human_readable_label=${image_tag_human_readable_label%_SLUG}
-        image_tag_human_readable_label=${image_tag_human_readable_label,,}
-        image_tag_human_readable_label=${image_tag_human_readable_label//_/ }
-        image_tag_human_readable_label=$(title_case ${image_tag_human_readable_label})
+        # Image tags may not contain the '+' character (from SemVer build metadata)
+        image_tag=${image_tag//+/.}
 
-        echo "- ${image_tag_human_readable_label}"  >> ${RELEASE_README_FILEPATH}
-        echo ""                                     >> ${RELEASE_README_FILEPATH}
-        echo "\`\`\`bash"                           >> ${RELEASE_README_FILEPATH}
-        echo "podman image pull ${IMAGE_PUSH_URI}"  >> ${RELEASE_README_FILEPATH}
-        echo "\`\`\`"                               >> ${RELEASE_README_FILEPATH}
-        echo ""                                     >> ${RELEASE_README_FILEPATH}
+
+        image_tag_description=${tag_var#CI_}
+        image_tag_description=${image_tag_description%_SLUG}
+        image_tag_description=${image_tag_description,,}
+        image_tag_description=${image_tag_description//_/ }
+        image_tag_description=$(title_case ${image_tag_description})
+
+        image_push_uri=${IMAGE_AS_BUILT_URI/%${IMAGE_AS_BUILT_VERSION}/${image_tag}}
+
+        echo "Copying image to ${image_push_uri}..."
+        skopeo copy --quiet docker://${IMAGE_AS_BUILT_URI}  docker://${image_push_uri}
+
+        echo "- ${image_tag_description}"             >> ${RELEASE_README_FILEPATH}
+        echo ""                                       >> ${RELEASE_README_FILEPATH}
+        echo "  \`\`\`bash"                           >> ${RELEASE_README_FILEPATH}
+        echo "  podman image pull ${image_push_uri}"  >> ${RELEASE_README_FILEPATH}
+        echo "  \`\`\`"                               >> ${RELEASE_README_FILEPATH}
+        echo ""                                       >> ${RELEASE_README_FILEPATH}
       done
   artifacts:
     paths:
